### ISSUE TITLE
Add username in response data

### ISSUE THREAD

**Issue by sanket143** [sinix-dev/sinix-mobile#10]
Sources
https://github.com/sinix-dev/sinix-android/blob/master/lib/store.dart#L24
https://github.com/sinix-dev/sinix-android/blob/master/lib/pages/game.dart#L40

**Comment by Starlight220** [comment]
What exactly is wanted here?

**Comment by sanket143** [comment]
Just need to add username field in the payload which is being sent to the server. The username can be accessed from the Store object. Also, issues tagged `SLoP-*` are reserved for SLoP contributors only. Have a look at the other projects, see if anything interests you.

**Comment by Starlight220** [comment]
Oh ok, no problem. I suggest putting the `SLoP` thing in a `CONTRIBUTING.md` file so others don't make the same mistake...

**Comment by sanket143** [comment]
Sure, thanks. Sorry for the inconvenience.

**Comment by ritvij14** [comment]
@sanket143 I would like to work on this. 
For solving this we just need to add the `username` field along with the x and y coordinates that are being already sent right?

**Comment by sanket143** [comment]
Sure :+1:
