### ISSUE TITLE
Add refresh functionality for available devices

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#11]
Use feather icons https://pub.dev/packages/feather_icons_flutter

**Comment by ritvij14** [comment]
I would like to work on this one. For now only the icon or should I add the complete functionality in it?

**Comment by janvig** [comment]
@ritvij14 It'll be easy to add functionality. You just need to call the `scan` function. Instead of adding an icon, adding "pull-to-refresh" would be much better.
