### ISSUE TITLE
Update JoyStick Page UI

### ISSUE THREAD

**Issue by sanket143** [sinix-dev/sinix-mobile#18]
**Note:** This issue is reserved for SLoP Contributors.

Color Values
`#FFFFFF`
`#DC143C`
`#DC143C`: `35% Opacity`
`#DC143C`: `52% Opacity`

![Android - 3](https://user-images.githubusercontent.com/26973649/94882348-6107e180-0485-11eb-8a76-a51a011fcea8.png)

**Comment by ritvij14** [comment]
Can I work on this? I am done with my last task.

**Comment by sanket143** [comment]
Wait for PRs linked with #10 and #11 to get merged.

**Comment by sanket143** [comment]
@ritvij14  Okay, you can take this up.
