### ISSUE TITLE
Add Icon before IP Address shown on Discover page

### ISSUE THREAD

**Issue by sanket143** [sinix-dev/sinix-mobile#19]
**Note:** This issue is reserved for SLoP Contributors.

The icon used here is from [Feather Icons](https://feathericons.com/). You can either use dart package for feather icon or .svg itself.

![Android - 2](https://user-images.githubusercontent.com/26973649/94884685-c19a1d00-048b-11eb-8027-06b54e322227.png)

**Comment by majeedyaseen** [comment]
Hi @sanket143 

I would like to work on this issue.

Thanks.

**Comment by sanket143** [comment]
@majeedyaseen Awesome

**Comment by Sirsho29** [comment]
Is the issue resolved?

**Comment by majeedyaseen** [comment]
> Is the issue resolved?

No please take it over @Sirsho29 my machine got some issues unfortunately :/ 

@sanket143 can reassign it to you.

**Comment by ritvij14** [comment]
@sanket143 can I take this, as it's only reserved for SLoP contributors?

**Comment by sanket143** [comment]
@ritvij14 yes

**Comment by sanket143** [comment]
@majeedyaseen If you face any issue, you can discuss on the #sinix-android channel on Discord or with us, we can help you.
