### ISSUE TITLE
Add our iconic splashscreen

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#2]
The following are splash screens for light and dark themes, respectively.

![sinix_light](https://user-images.githubusercontent.com/34552448/93711906-8f291f80-fb6f-11ea-9599-e4f96c7dec46.jpeg)
![sinix_dark](https://user-images.githubusercontent.com/34552448/93711908-90f2e300-fb6f-11ea-82b7-934cf980563c.jpeg)

**Comment by mayurpatilll** [comment]
Where can I get to see,  how your iconic splashscreen looks like ?

**Comment by janvig** [comment]
Here you go!
![sinix_light](https://user-images.githubusercontent.com/34552448/93711906-8f291f80-fb6f-11ea-9599-e4f96c7dec46.jpeg)
![sinix_dark](https://user-images.githubusercontent.com/34552448/93711908-90f2e300-fb6f-11ea-82b7-934cf980563c.jpeg)

**Comment by janvig** [comment]
@mayurpatilll I've updated the description, have a look at the designs.

**Comment by mayurpatilll** [comment]
@janvig I have added the iconic splash screen for both light and dark theme and created a pull request.

**Comment by janvig** [comment]
@mayurpatilll Have you registered for [SLoP](https://slop.dscdaiict.in/)?

**Comment by mayurpatilll** [comment]
@janvig I will be registering today, the proposal is almost ready.

**Comment by mayurpatilll** [comment]
@janvig How will I know if I am a part of SLoP or not ? I registered and submitted the proposal on 21 Sept, and have not received any reply mail from SLoP.

**Comment by janvig** [comment]
@mayurpatilll The committee will inform you once they have reviewed all the applications. Till then keep exploring :)

**Comment by mayurpatilll** [comment]
@janvig Okay, Thanks !
