### ISSUE TITLE
Update UI of Onboarding page

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#23]
![image](https://user-images.githubusercontent.com/34552448/95079968-ff6d9e80-0734-11eb-8250-43f7c590aecc.png)

**Comment by ritvij14** [comment]
@janvig for this we only have to remove the profile picture SVG and replace with the SINIX logo and add an enter button right? Could you please explain what the enter button should do? (change screen, send some data, etc.)

**Comment by janvig** [comment]
@ritvij14 Yes. On pressing the _Enter_ button the username is updated in store.dart and the user lands upon the _Available Devices_ screen.

**Comment by ritvij14** [comment]
@janvig alright, understood. Thanks for the clarification. Can I work on this?

**Comment by sanket143** [comment]
Sure
