### ISSUE TITLE
The getter 'stream' was called on null

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#3]
When trying to connect with a dead server, shows this error 
```Another exception was thrown: NoSuchMethodError: The getter 'stream' was called on null.```

**Comment by GajjarMiten** [comment]
Hey @sanket143!
I would like to work on it.

I think when we call a dead server from `http.post()` it will throw the timeout error. By handling that error using `timeout()`
we can send a response with timeout status code and after checking that status we can try to connect with the server or we can simply show the alert dialogue.
 
what do you think about this?
can I go with this way for this issue?

**Comment by sanket143** [comment]
Sounds good :+1:
