### ISSUE TITLE
Add status bar on top of the joystick

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#33]
Note: This issue is reserved for SLoP contributors.

Color Values
`#FFFFFF`
`#DC143C`: `52% Opacity`

![Android - 3](https://user-images.githubusercontent.com/26973649/94882348-6107e180-0485-11eb-8a76-a51a011fcea8.png)

**Comment by ritvij14** [comment]
For now, it will only be dummy text, or is the name of game coming from the backend?

**Comment by sanket143** [comment]
Yes it'll be a dummy text.

**Comment by ritvij14** [comment]
Ok, then I will start working on this. Please assign it to me.
