### ISSUE TITLE
Add a page to ask for Username

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#7]
**Note:** This issue is reserved for SLoP Contributors.

There is no login or sign up. The username is how Sinix will identify the user.

**Comment by GajjarMiten** [comment]
Hey @janvig!
I would like to work on it.

do we need add a page for login and singup?
or just we have to ask for username from user?

**Comment by janvig** [comment]
Hello @GajjarMiten, go ahead solving this issue.
We just need a username to be recognized locally. No need to register because there is no communication beyond the Local Network. Also, it should update the `username` in `store.dart`.
