### ISSUE TITLE
Add and apply Roboto font in all text

### ISSUE THREAD

**Issue by janvig** [sinix-dev/sinix-mobile#9]

**Comment by ritvij14** [comment]
I would like to work on this.

**Comment by ritvij14** [comment]
@janvig the app has MaterialApp so the font would automatically be Roboto, wouldn't it? Or should I explicitly set it as a default font for the whole app using `ThemeData`?

**Comment by janvig** [comment]
@ritvij14 The default font depends on the OS, Roboto for Android but SF for iOS. So go ahead with explicitly setting it to Roboto.
